-- Generated by unmodified cogg.cpp Phase 2 (b4f9b26); immutable v1 history fixture.
PRAGMA application_id=1129269063;
PRAGMA user_version=1;
BEGIN TRANSACTION;
CREATE TABLE attempts(
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE,
 subject TEXT NOT NULL REFERENCES subjects(id), parent TEXT NOT NULL,
 occasion TEXT NOT NULL REFERENCES occasions(id), admitted_at INTEGER NOT NULL,
 body TEXT NOT NULL, status TEXT NOT NULL, error TEXT NOT NULL DEFAULT '');
INSERT INTO "attempts" VALUES(1,'02ef9924f4752d66ad156d364b7715298fa70972c098b557250f7abb6c675e87','legacy','e2ee93809a5b3a5196e670d5c5406e010a350ee416df812b6f7eb9874090a75c','ff4f4e8fc4b33677449e6fb5c7757dc190d942c7d6f5dcf037058eb1158e5394',1788786671643,'{"admitted_at":1788786671643,"backend":"demo-counter/v1","nonce":"2a23369615946bea29e40e5792ccfdfb","occasion":"ff4f4e8fc4b33677449e6fb5c7757dc190d942c7d6f5dcf037058eb1158e5394","parent":"e2ee93809a5b3a5196e670d5c5406e010a350ee416df812b6f7eb9874090a75c","prior_unsettled":false,"schema":1,"subject":"legacy","tick":0}','committed','');
CREATE TABLE commits(
 id TEXT PRIMARY KEY, subject TEXT NOT NULL REFERENCES subjects(id),
 tick INTEGER NOT NULL, body TEXT NOT NULL, UNIQUE(subject,tick));
INSERT INTO "commits" VALUES('e2ee93809a5b3a5196e670d5c5406e010a350ee416df812b6f7eb9874090a75c','legacy',0,'{"created_at":1788786671634,"limits":{"max_attempts":10,"min_wake_ms":1,"period_ms":1000},"memory":{},"nonce":"73cc6d0606f09901283ef1f27bb26a3e","parent":null,"schema":1,"subject":"legacy","tick":0,"wake_at":null}');
INSERT INTO "commits" VALUES('b5e1a7c98a2a84e7f81caca653087d6d10f71117b9c6e471c82e01142d22221d','legacy',1,'{"attempt":"02ef9924f4752d66ad156d364b7715298fa70972c098b557250f7abb6c675e87","committed_at":1788786671643,"memory":{"counter":1},"occasion":"ff4f4e8fc4b33677449e6fb5c7757dc190d942c7d6f5dcf037058eb1158e5394","parent":"e2ee93809a5b3a5196e670d5c5406e010a350ee416df812b6f7eb9874090a75c","proposal":{"kind":"reflection","memory":[{"key":"counter","value":1}],"text":"","wake_after_ms":null},"schema":1,"subject":"legacy","tick":1,"wake_at":null}');
CREATE TABLE occasions(
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE,
 subject TEXT NOT NULL REFERENCES subjects(id), key TEXT NOT NULL,
 kind TEXT NOT NULL, parent TEXT NOT NULL, body TEXT NOT NULL,
 consumed TEXT, UNIQUE(subject,key));
INSERT INTO "occasions" VALUES(1,'ff4f4e8fc4b33677449e6fb5c7757dc190d942c7d6f5dcf037058eb1158e5394','legacy','system:created','created','e2ee93809a5b3a5196e670d5c5406e010a350ee416df812b6f7eb9874090a75c','{"key":"system:created","kind":"created","parents":["e2ee93809a5b3a5196e670d5c5406e010a350ee416df812b6f7eb9874090a75c"],"payload":{},"received_at":1788786671634,"schema":1,"subject":"legacy"}','b5e1a7c98a2a84e7f81caca653087d6d10f71117b9c6e471c82e01142d22221d');
CREATE TABLE subjects(
 id TEXT PRIMARY KEY, tick INTEGER NOT NULL, head TEXT NOT NULL,
 memory TEXT NOT NULL, wake TEXT NOT NULL, limits TEXT NOT NULL,
 accounting_wall INTEGER NOT NULL);
INSERT INTO "subjects" VALUES('legacy',1,'b5e1a7c98a2a84e7f81caca653087d6d10f71117b9c6e471c82e01142d22221d','{"counter":1}','null','{"max_attempts":10,"min_wake_ms":1,"period_ms":1000}',1788786671643);
CREATE INDEX attempts_budget ON attempts(subject,admitted_at);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('occasions',1);
INSERT INTO "sqlite_sequence" VALUES('attempts',1);
COMMIT;
