-- Generated by unmodified Phase 4 v0.5.0 CLI (16e2bf9).
BEGIN TRANSACTION;
CREATE TABLE attempts(
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE,
 subject TEXT NOT NULL REFERENCES subjects(id), parent TEXT NOT NULL,
 occasion TEXT NOT NULL REFERENCES occasions(id), admitted_at INTEGER NOT NULL,
 body TEXT NOT NULL, status TEXT NOT NULL, error TEXT NOT NULL DEFAULT '');
INSERT INTO "attempts" VALUES(1,'1d1e5bb9373bbba21818593c0ea9c3928cacd87d1fbe75fba68e03fd6e6a7815','legacy','d4fccc2118d6fbc864989a781a1fbc64e09da894353b9b3cb61155cfddcbad0b','fa0ea722fb84d0f84f39006fc8a87abc904b368c150d6d1e0b6e916340dc74a9',1788880291702,'{"admitted_at":1788880291702,"backend":"demo-counter/v1","nonce":"d0d5f3648f8030e5c0b6d249e3451626","occasion":"fa0ea722fb84d0f84f39006fc8a87abc904b368c150d6d1e0b6e916340dc74a9","parent":"d4fccc2118d6fbc864989a781a1fbc64e09da894353b9b3cb61155cfddcbad0b","prior_unsettled":false,"schema":3,"subject":"legacy","temporal":{"admission":{"accounting_at":1788880291702,"budget":{"eligible_at":1788880291702,"floor_at":1788880291702,"limit":100,"period_ms":1000000,"quota_at":1788880291702,"through_seq":0,"used":0},"eligible_at":1788880291702,"head":"d4fccc2118d6fbc864989a781a1fbc64e09da894353b9b3cb61155cfddcbad0b","occasion":{"id":"fa0ea722fb84d0f84f39006fc8a87abc904b368c150d6d1e0b6e916340dc74a9","kind":"created","payload":{}},"status":"ready","tick":0,"wake_at":null,"wall_observed_at":1788880291702,"wall_rollback_ms":0},"clock":{"clock_id":"cogg:commit:d4fccc2118d6fbc864989a781a1fbc64e09da894353b9b3cb61155cfddcbad0b","grain_epoch":"cogg:committed-transition/v1","membership":"verified subject commit parent chain; genesis is coordinate zero","origin":"d4fccc2118d6fbc864989a781a1fbc64e09da894353b9b3cb61155cfddcbad0b","unit":"committed_transition"},"coordinate":0,"previous_wake":null,"wake_lateness_ms":null},"tick":0,"wall_observed_at":1788880291702}','committed','');
CREATE TABLE commits(
 id TEXT PRIMARY KEY, subject TEXT NOT NULL REFERENCES subjects(id),
 tick INTEGER NOT NULL, body TEXT NOT NULL, UNIQUE(subject,tick));
INSERT INTO "commits" VALUES('d4fccc2118d6fbc864989a781a1fbc64e09da894353b9b3cb61155cfddcbad0b','legacy',0,'{"created_at":1788880291691,"limits":{"max_attempts":100,"max_wake_ms":31536000000,"min_wake_ms":1,"period_ms":1000000},"memory":{},"nonce":"a7395bc891ab97ef7c67b48541e2c752","parent":null,"schema":3,"subject":"legacy","tick":0,"wake_at":null}');
INSERT INTO "commits" VALUES('e7fbc61afdfadb7827adf0ab00aa581a10aa4db299297b897f9c1ef0cda685bc','legacy',1,'{"attempt":"1d1e5bb9373bbba21818593c0ea9c3928cacd87d1fbe75fba68e03fd6e6a7815","committed_at":1788880291704,"inference_elapsed_ms":0,"memory":{"counter":1},"occasion":"fa0ea722fb84d0f84f39006fc8a87abc904b368c150d6d1e0b6e916340dc74a9","parent":"d4fccc2118d6fbc864989a781a1fbc64e09da894353b9b3cb61155cfddcbad0b","proposal":{"kind":"reflection","memory":[{"key":"counter","value":1}],"text":"","wake_after_ms":null},"schema":3,"subject":"legacy","tick":1,"wake_at":null,"wake_plan":{"budget":{"eligible_at":1788880291704,"floor_at":1788880291704,"limit":100,"period_ms":1000000,"quota_at":1788880291704,"through_seq":1,"used":1},"decided_at":1788880291704,"granted_after_ms":null,"granted_at":null,"policy":"cogg:wake/v2","reasons":["waiting_external"],"requested_after_ms":null,"requested_at":null},"wall_observed_at":1788880291704}');
CREATE TABLE memory_entries(id TEXT PRIMARY KEY,subject TEXT NOT NULL REFERENCES subjects(id),key TEXT NOT NULL,tick INTEGER NOT NULL,commit_id TEXT NOT NULL,body TEXT NOT NULL,current INTEGER NOT NULL);
PRAGMA writable_schema=ON;
INSERT INTO sqlite_master(type,name,tbl_name,rootpage,sql)VALUES('table','memory_fts','memory_fts',0,'CREATE VIRTUAL TABLE memory_fts USING fts5(id UNINDEXED,subject UNINDEXED,key,text,tokenize=''unicode61'')');
CREATE TABLE 'memory_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;
INSERT INTO "memory_fts_config" VALUES('version',4);
CREATE TABLE 'memory_fts_content'(id INTEGER PRIMARY KEY, c0, c1, c2, c3);
CREATE TABLE 'memory_fts_data'(id INTEGER PRIMARY KEY, block BLOB);
INSERT INTO "memory_fts_data" VALUES(1,X'');
INSERT INTO "memory_fts_data" VALUES(10,X'00000000000000');
CREATE TABLE 'memory_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
CREATE TABLE 'memory_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
CREATE TABLE memory_links(subject TEXT NOT NULL,note TEXT NOT NULL,source TEXT NOT NULL,covers INTEGER NOT NULL,PRIMARY KEY(note,source));
CREATE TABLE occasions(
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE,
 subject TEXT NOT NULL REFERENCES subjects(id), key TEXT NOT NULL,
 kind TEXT NOT NULL, parent TEXT NOT NULL, body TEXT NOT NULL,
 consumed TEXT, UNIQUE(subject,key));
INSERT INTO "occasions" VALUES(1,'fa0ea722fb84d0f84f39006fc8a87abc904b368c150d6d1e0b6e916340dc74a9','legacy','system:created','created','d4fccc2118d6fbc864989a781a1fbc64e09da894353b9b3cb61155cfddcbad0b','{"key":"system:created","kind":"created","parents":["d4fccc2118d6fbc864989a781a1fbc64e09da894353b9b3cb61155cfddcbad0b"],"payload":{},"received_at":1788880291691,"schema":1,"subject":"legacy"}','e7fbc61afdfadb7827adf0ab00aa581a10aa4db299297b897f9c1ef0cda685bc');
CREATE TABLE subjects(
 id TEXT PRIMARY KEY, tick INTEGER NOT NULL, head TEXT NOT NULL,
 memory TEXT NOT NULL, wake TEXT NOT NULL, limits TEXT NOT NULL,
 accounting_wall INTEGER NOT NULL);
INSERT INTO "subjects" VALUES('legacy',1,'e7fbc61afdfadb7827adf0ab00aa581a10aa4db299297b897f9c1ef0cda685bc','{"counter":1}','null','{"max_attempts":100,"max_wake_ms":31536000000,"min_wake_ms":1,"period_ms":1000000}',1788880291704);
CREATE INDEX attempts_budget ON attempts(subject,admitted_at);
CREATE INDEX memory_current ON memory_entries(subject,current,tick);
CREATE INDEX memory_keys ON memory_entries(subject,key,tick);
CREATE INDEX memory_sources ON memory_links(source);
PRAGMA writable_schema=OFF;
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('occasions',1);
INSERT INTO "sqlite_sequence" VALUES('attempts',1);
COMMIT;
PRAGMA application_id=1129269063;
PRAGMA user_version=3;
